const iconMapping = {
  Male: { icon: "mars", verb: "be" },
  Female: { icon: "venus", verb: "be" },
  "2-11": { icon: "birthday-cake", verb: "be", modifier: "years old" },
  "18-24": { icon: "birthday-cake", verb: "be", modifier: "years old" },
  "25-34": { icon: "birthday-cake", verb: "be", modifier: "years old" },
  "35-44": { icon: "birthday-cake", verb: "be", modifier: "years old" },
  "45-54": { icon: "birthday-cake", verb: "be", modifier: "years old" },
  "55-64": { icon: "birthday-cake", verb: "be", modifier: "years old" },
  "65+": { icon: "birthday-cake", verb: "be", modifier: "years old" },
  "<$75k": { icon: "dollar-sign", verb: "earn" },
  "$75-<$125k": { icon: "dollar-sign", verb: "earn" },
  "$125k+": { icon: "dollar-sign", verb: "earn" },
  Hispanic: { icon: "user", verb: "be" },
  Asian: { icon: "user", verb: "be" },
  "African American": { icon: "user", verb: "be" },
  White: { icon: "user", verb: "be" },
  Married: { icon: "ring", verb: "be" },
  Single: { icon: "heart", verb: "be" },
  Sports: { icon: "baseball-ball", verb: "read content about" },
  Fashion: { icon: "tshirt", verb: "read content about" },
  Travel: { icon: "plane", verb: "read content about" },
  Leisure: { icon: "umbrella-beach", verb: "read content about" },
  "Art & Artists": { icon: "paint-brush", verb: "read content about" },
  Design: { icon: "ruler-horizontal", verb: "read content about" },
  Food: { icon: "hamburger", verb: "read content about" },
  Shopping: { icon: "shopping-bag", verb: "read content about" },
  "International Affairs": { icon: "globe", verb: "read content about" },
  Law: { icon: "gavel", verb: "read content about" },
  Politics: { icon: "vote-yea", verb: "read content about" },
  News: { icon: "newspaper", verb: "read content about" },
  Technology: { icon: "sim-card", verb: "read content about" },
  "Books & Read content abouting": { icon: "book", verb: "read content about" },
  Business: { icon: "briefcase", verb: "read content about" },
  "Dining Out": { icon: "utensils", verb: "read content about" },
  Music: { icon: "music", verb: "read content about" },
  Beauty: { icon: "spa", verb: "read content about" },
  Other: { icon: "circle", verb: "read content about" },
  Family: { icon: "baby", verb: "read content about" },
  Television: { icon: "tv", verb: "read content about" },
  Activism: { icon: "walking", verb: "read content about" },
  Film: { icon: "video", verb: "read content about" },
  Science: { icon: "flask", verb: "read content about" },
  Gaming: { icon: "gamepad", verb: "read content about" },
  Health: { icon: "heartbeat", verb: "read content about" }
};

export default iconMapping;
